### ISSUE TITLE
Linux installer not working (Ubuntu 22.04)

### ISSUE THREAD

**Issue by fdlouky** [Sewdohe/NeoCode#19]
I've cloned the repo and after running `./NeocodeInstallerLinux --deps --install-packer` in NeoCode/neoCodeInstaller I get the following

```
Checking if nvim is installed
nvim is installed! Located at: /usr/bin/nvim
Checking if fzf is installed
Uh oh! Looks like fzf is not installed. Let's mark it for installation...
Checking if rg is installed
Uh oh! Looks like rg is not installed. Let's mark it for installation...
thread 'main' panicked at 'Error: failed to install fzf: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/helpers.rs:444:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fdlouky** [comment]
I've run `RUST_BACKTRACE=full ./NeocodeInstallerLinux --deps --install-packer` and get the following

```
Checking if nvim is installed
Uh oh! Looks like nvim is not installed. Let's mark it for installation...
Checking if fzf is installed
Uh oh! Looks like fzf is not installed. Let's mark it for installation...
Checking if rg is installed
rg is installed! Located at: /usr/bin/rg
thread 'main' panicked at 'Error: failed to tap 'brukberhane/brew': Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/helpers.rs:429:18
stack backtrace:
   0:     0x55f2017c1a6c - std::backtrace_rs::backtrace::libunwind::trace::h09f7e4e089375279
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55f2017c1a6c - std::backtrace_rs::backtrace::trace_unsynchronized::h1ec96f1c7087094e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55f2017c1a6c - std::sys_common::backtrace::_print_fmt::h317b71fc9a5cf964
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x55f2017c1a6c - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he3555b48e7dfe7f0
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x55f2017e2ddc - core::fmt::write::h513b07ca38f4fb1b
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/fmt/mod.rs:1149:17
   5:     0x55f2017be7a5 - std::io::Write::write_fmt::haf8c932b52111354
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/io/mod.rs:1697:15
   6:     0x55f2017c33f0 - std::sys_common::backtrace::_print::h195c38364780a303
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x55f2017c33f0 - std::sys_common::backtrace::print::hc09dfdea923b6730
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x55f2017c33f0 - std::panicking::default_hook::{{closure}}::hb2e38ec0d91046a3
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:211:50
   9:     0x55f2017c2fa5 - std::panicking::default_hook::h60284635b0ad54a8
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:228:9
  10:     0x55f2017c3aa4 - std::panicking::rust_panic_with_hook::ha677a669fb275654
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:606:17
  11:     0x55f2017c3580 - std::panicking::begin_panic_handler::{{closure}}::h976246fb95d93c31
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:502:13
  12:     0x55f2017c1f14 - std::sys_common::backtrace::__rust_end_short_backtrace::h38077ee5b7b9f99a
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x55f2017c34e9 - rust_begin_unwind
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:498:5
  14:     0x55f2017534a1 - core::panicking::panic_fmt::h35f3a62252ba0fd2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/panicking.rs:107:14
  15:     0x55f201753533 - core::result::unwrap_failed::hb53671404b9e33c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/result.rs:1613:5
  16:     0x55f201756650 - neocode_installer::helpers::funcs::check_dependencies::h8d93286f0336d82a
  17:     0x55f20175aff7 - neocode_installer::main::h85fa3794c6baefe1
  18:     0x55f2017585d3 - std::sys_common::backtrace::__rust_begin_short_backtrace::hc18e1a28329d13fd
  19:     0x55f20175c9a9 - std::rt::lang_start::{{closure}}::h10031702ab55ca32
  20:     0x55f2017c16fb - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h7e688d7cdfeb7e00
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:259:13
  21:     0x55f2017c16fb - std::panicking::try::do_call::h4be824d2350b44c9
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  22:     0x55f2017c16fb - std::panicking::try::h0a6fc7affbe5088d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  23:     0x55f2017c16fb - std::panic::catch_unwind::h22c320f732ec805e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  24:     0x55f2017c16fb - std::rt::lang_start_internal::{{closure}}::hd38309c108fe679d
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:48
  25:     0x55f2017c16fb - std::panicking::try::do_call::h8fcaf501f097a28e
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:406:40
  26:     0x55f2017c16fb - std::panicking::try::h20e906825f98acc1
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:370:19
  27:     0x55f2017c16fb - std::panic::catch_unwind::h8c5234dc632124ef
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panic.rs:133:14
  28:     0x55f2017c16fb - std::rt::lang_start_internal::hc4dd8cd3ec4518c2
                               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/rt.rs:128:20
  29:     0x55f20175bcc2 - main
  30:     0x7f389c233d90 - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  31:     0x7f389c233e40 - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:392:3
  32:     0x55f201753bee - _start
  33:                0x0 - <unknown>
```

**Comment by Sewdohe** [comment]
Hmm I suspect fzf isn't available in Ubuntu packages :/ I can do a fix for it tomorrow. It's 3am here. Thanks for raising the issue though

Just out of curiosity, how'd you find out about Neocode?

**Comment by fdlouky** [comment]
> Hmm I suspect fzf isn't available in Ubuntu packages :/ I can do a fix for it tomorrow. It's 3am here. Thanks for raising the issue though
Thanks 🙏 I'd love to use it in my Ubuntu... 💪
> Just out of curiosity, how'd you find out about Neocode?
I've read about it in reddit and I really want to have my nvim with this configuration 😁🙌

**Comment by Sewdohe** [comment]
I'm terribly sorry it's been so long but I've re-written the installer to use a simple python script. It's much more robust and reliable than before. If you'd like to try again I am back active with this project :)
